### PR TITLE
Replace `changelog render` with `changelog preview`

### PR DESCRIPTION
**Pull request by TheoryOfNekomata**
Seeing as this command previews the changelog in Markdown, it's more
intuitive to call the command as such.

### CODE REVIEW

**Comment by migelfn** [comment]
Looks good!

**Comment by xdgimf** [comment]
+1

**Comment by clrke** [comment]
This is the fix for https://github.com/whitecloakph/changelog-sh/issues/2 ?

**Comment by TheoryOfNekomata** [comment]
Yes, it is.

**Pull request merged**
